### ISSUE TITLE
Installing Issue (public/lib)

### ISSUE THREAD

**Issue by rdeyo1129** [ianfab/fairy-stockfish-nnue-wasm-demo#6]
Hello,

I'm trying to import FSF wasm npm package like you did into a project I'm working on and I've been following along with your repo as an example. I'm running into an issue though with the `npm run link-lib` command. I brought the script over to my package.json in my project's root folder and when running that it doesn't pick up on anything because there is no package in the public/lib (that I tried creating) directory. I see that folder has been ignored in your git ignore. Are you able to give me some insight on what you did in that folder? Did you initialize a package json there or was it something that you brought in from the wasm npm package/repo?

Thanks for your time.

**Comment by ianfab** [comment]
Somehow only noticed this issue now. If this is still open, the link-lib (or copy-lib) relies on that the fairy-stockfish-nnue.wasm NPM package is installed, see the readme and the package.json.

**Comment by rdeyo1129** [comment]
Thanks for the reply, was on hold for a bit and just got back to this. I'll give this another shot.
